version: '3.8'

services:
  database:
    container_name: "postgres"
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    networks:
      - backend

  fastapi:
    container_name: "fastapi"
    build:
      context: .
      dockerfile: DockerfileFastAPI
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/src/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - database
    networks:
      - backend

#  bot:
#    container_name: "bot"
#    build:
#      context: .
#      dockerfile: DockerfileBot
#    command: python bot.py
#    restart: always
#    volumes:
#      - ./.env:/src/.env
#    ports:
#      - "8080:8080"
#    depends_on:
#      - fastapi
#    networks:
#      - backend
#
networks:
  backend:
    driver: bridge
