version: '3.8'

services:
  database:
    container_name: "postgres"
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db_data/:/var/lib/postgresql/data

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    #restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/src/.env
    depends_on:
      - database

  bot:
    container_name: "bot"
    build: ./bot
    command: python main.py
    #restart: always
    volumes:
      - ./.env:/src/.env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - backend
